//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECatalog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECatalog.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is deleted..
        /// </summary>
        public static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is not translated.
        /// </summary>
        public static string CategoryIsNotTranslated {
            get {
                return ResourceManager.GetString("CategoryIsNotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category must have at least one item..
        /// </summary>
        public static string CategoryItemsDoesNotActivated {
            get {
                return ResourceManager.GetString("CategoryItemsDoesNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is already exist..
        /// </summary>
        public static string CategoryNameAlreadyExist {
            get {
                return ResourceManager.GetString("CategoryNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name cannot exceed 300 characters..
        /// </summary>
        public static string CategoryNameExceedLemgth {
            get {
                return ResourceManager.GetString("CategoryNameExceedLemgth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found..
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category image is requied.
        /// </summary>
        public static string EmptyCategoryImage {
            get {
                return ResourceManager.GetString("EmptyCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter category name..
        /// </summary>
        public static string EmptyCategoryName {
            get {
                return ResourceManager.GetString("EmptyCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter item description..
        /// </summary>
        public static string EmptyItemDescription {
            get {
                return ResourceManager.GetString("EmptyItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter item name..
        /// </summary>
        public static string EmptyItemName {
            get {
                return ResourceManager.GetString("EmptyItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter item pricce..
        /// </summary>
        public static string EmptyItemPrice {
            get {
                return ResourceManager.GetString("EmptyItemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter menu name..
        /// </summary>
        public static string EmptyMenuName {
            get {
                return ResourceManager.GetString("EmptyMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter admin password for the restaurant..
        /// </summary>
        public static string EmptyRestaurantAdminPassword {
            get {
                return ResourceManager.GetString("EmptyRestaurantAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter admin username for the restaurant..
        /// </summary>
        public static string EmptyRestaurantAdminUserName {
            get {
                return ResourceManager.GetString("EmptyRestaurantAdminUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter restaurant description..
        /// </summary>
        public static string EmptyRestaurantDescription {
            get {
                return ResourceManager.GetString("EmptyRestaurantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant logo is required..
        /// </summary>
        public static string EmptyRestaurantLogo {
            get {
                return ResourceManager.GetString("EmptyRestaurantLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter restaurant name..
        /// </summary>
        public static string EmptyRestaurantName {
            get {
                return ResourceManager.GetString("EmptyRestaurantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter restaurant type name..
        /// </summary>
        public static string EmptyRestaurantType {
            get {
                return ResourceManager.GetString("EmptyRestaurantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter waiter username for the restaurant..
        /// </summary>
        public static string EmptyRestaurantWaiterUserName {
            get {
                return ResourceManager.GetString("EmptyRestaurantWaiterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter side item name..
        /// </summary>
        public static string EmptySideItemName {
            get {
                return ResourceManager.GetString("EmptySideItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size allowed is 20MB.
        /// </summary>
        public static string ImageExceedSize {
            get {
                return ResourceManager.GetString("ImageExceedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type..
        /// </summary>
        public static string InvalidImageType {
            get {
                return ResourceManager.GetString("InvalidImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price..
        /// </summary>
        public static string InvalidItemPrice {
            get {
                return ResourceManager.GetString("InvalidItemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid side item value..
        /// </summary>
        public static string InvalidSideItemValue {
            get {
                return ResourceManager.GetString("InvalidSideItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is deleted..
        /// </summary>
        public static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not translated..
        /// </summary>
        public static string ItemIsNotTranslated {
            get {
                return ResourceManager.GetString("ItemIsNotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name is already exist..
        /// </summary>
        public static string ItemNameAlreadyExist {
            get {
                return ResourceManager.GetString("ItemNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name cannot exceed 300 characters..
        /// </summary>
        public static string ItemNameExceedLength {
            get {
                return ResourceManager.GetString("ItemNameExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu must have at least one activated category..
        /// </summary>
        public static string MenuCategoriesDoesNotActivated {
            get {
                return ResourceManager.GetString("MenuCategoriesDoesNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu is deleted..
        /// </summary>
        public static string MenuDeleted {
            get {
                return ResourceManager.GetString("MenuDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu is not translated.
        /// </summary>
        public static string MenuIsNotTranslated {
            get {
                return ResourceManager.GetString("MenuIsNotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu name is already exist.
        /// </summary>
        public static string MenuNameAlreadyExist {
            get {
                return ResourceManager.GetString("MenuNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu name cannot exceed 300 characters..
        /// </summary>
        public static string MenuNameExceedLength {
            get {
                return ResourceManager.GetString("MenuNameExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu not found.
        /// </summary>
        public static string MenuNotFound {
            get {
                return ResourceManager.GetString("MenuNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant admin is not found..
        /// </summary>
        public static string RestaurantAdminNotFound {
            get {
                return ResourceManager.GetString("RestaurantAdminNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length Must be 8-25 characters..
        /// </summary>
        public static string RestaurantAdminPasswordLengthNotMatched {
            get {
                return ResourceManager.GetString("RestaurantAdminPasswordLengthNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already exist.
        /// </summary>
        public static string RestaurantAdminUserNameAlreadyExist {
            get {
                return ResourceManager.GetString("RestaurantAdminUserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant is deleted..
        /// </summary>
        public static string RestaurantDeleted {
            get {
                return ResourceManager.GetString("RestaurantDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant is not ready.
        /// </summary>
        public static string RestaurantIsNotReady {
            get {
                return ResourceManager.GetString("RestaurantIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant is not translated.
        /// </summary>
        public static string RestaurantIsNotTranslated {
            get {
                return ResourceManager.GetString("RestaurantIsNotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant must have at least one activated menu..
        /// </summary>
        public static string RestaurantMenuDoesNotActivated {
            get {
                return ResourceManager.GetString("RestaurantMenuDoesNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant name is already exist.
        /// </summary>
        public static string RestaurantNameAlreadyExist {
            get {
                return ResourceManager.GetString("RestaurantNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant name cannot exceed 300 characters..
        /// </summary>
        public static string RestaurantNameExceedLength {
            get {
                return ResourceManager.GetString("RestaurantNameExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant not found..
        /// </summary>
        public static string RestaurantNotFound {
            get {
                return ResourceManager.GetString("RestaurantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant type is already exist..
        /// </summary>
        public static string RestaurantTypeAlreadyExist {
            get {
                return ResourceManager.GetString("RestaurantTypeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant type cannot exceed 300 characters..
        /// </summary>
        public static string RestaurantTypeExceedLength {
            get {
                return ResourceManager.GetString("RestaurantTypeExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant type is not translated.
        /// </summary>
        public static string RestaurantTypeIsNotTranslated {
            get {
                return ResourceManager.GetString("RestaurantTypeIsNotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant type not found..
        /// </summary>
        public static string RestaurantTypeNotFound {
            get {
                return ResourceManager.GetString("RestaurantTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant name cannot exceed 100 characters..
        /// </summary>
        public static string RestaurantWaiterNameExceedLength {
            get {
                return ResourceManager.GetString("RestaurantWaiterNameExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side item is deleted.
        /// </summary>
        public static string SideItemDeleted {
            get {
                return ResourceManager.GetString("SideItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side item is not translated..
        /// </summary>
        public static string SideItemIsNotTranslated {
            get {
                return ResourceManager.GetString("SideItemIsNotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side item is already exists..
        /// </summary>
        public static string SideItemNameAlreadyExist {
            get {
                return ResourceManager.GetString("SideItemNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side item cannot exceed 100 characters..
        /// </summary>
        public static string SideItemNameExceedLength {
            get {
                return ResourceManager.GetString("SideItemNameExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side item name must be more than 3 characters..
        /// </summary>
        public static string SideItemNameMinimumLength {
            get {
                return ResourceManager.GetString("SideItemNameMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side item not found.
        /// </summary>
        public static string SideItemNotFound {
            get {
                return ResourceManager.GetString("SideItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size is deleted.
        /// </summary>
        public static string SizeDeleted {
            get {
                return ResourceManager.GetString("SizeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size is not translated..
        /// </summary>
        public static string SizeIsNotTranslated {
            get {
                return ResourceManager.GetString("SizeIsNotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size name is already exist.
        /// </summary>
        public static string SizeNameAlreadyExist {
            get {
                return ResourceManager.GetString("SizeNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size name cannot exceed 100 characters..
        /// </summary>
        public static string SizeNameExceedLength {
            get {
                return ResourceManager.GetString("SizeNameExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size name must be more than 3 characters..
        /// </summary>
        public static string SizeNameMinimumLength {
            get {
                return ResourceManager.GetString("SizeNameMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size is not found.
        /// </summary>
        public static string SizeNotFound {
            get {
                return ResourceManager.GetString("SizeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is not supported..
        /// </summary>
        public static string UnSupportedLanguage {
            get {
                return ResourceManager.GetString("UnSupportedLanguage", resourceCulture);
            }
        }
    }
}
